import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

function read(path: string) {
  const fullPath = join(process.cwd(), path);
  assert(existsSync(fullPath), `${path} must exist.`);
  return readFileSync(fullPath, "utf-8");
}

function includes(label: string, value: string, expected: string) {
  assert(value.includes(expected), `${label} must include: ${expected}`);
}

const files: Record<string, string> = {
  packageJson: read("package.json"),
  versionRoute: read("app/api/version/route.ts"),
  healthRoute: read("app/api/health/route.ts"),
  monitorReport: read("scripts/mragent-monitor-report.mjs"),
  monitorWorkflow: read(".github/workflows/mragent-monitor.yml"),
  incidentProbe: read("scripts/production-domain-incident.mjs"),
  incidentWorkflow: read(".github/workflows/mragent-domain-incident.yml"),
  growthPulse: read("scripts/mragent-growth-pulse.mjs"),
  growthWorkflow: read(".github/workflows/mragent-growth-pulse.yml"),
  shortDigest: read("scripts/mragent-short-digest.mjs"),
  vercelIgnore: read("scripts/vercel-ignore-build.mjs"),
  vercelGuardWorkflow: read(".github/workflows/vercel-guard-verify.yml"),
  manualDeployWorkflow: read(".github/workflows/manual-vercel-production.yml"),
  aliasReadyWorkflow: read(".github/workflows/vercel-alias-ready-deployment.yml"),
  liveRevenueVerifier: read("scripts/verify-live-revenue-surface.mjs"),
  sendOwnerReport: read("scripts/send-hourly-owner-report.ts"),
  reportSchema: read("site/automation/report-schema.yml"),
  vercelRunbook: read("site/automation/vercel-build-limit-runbook.yml"),
};

const checks: Array<[label: string, file: string, expected: string]> = [
  ["package scripts", "packageJson", '"incident:domain"'],
  ["package scripts", "packageJson", '"growth:pulse"'],
  ["package scripts", "packageJson", '"report:digest"'],
  ["package scripts", "packageJson", '"verify:live-revenue"'],
  ["version route", "versionRoute", "VERCEL_GIT_COMMIT_SHA"],
  ["version route", "versionRoute", "NEXT_PUBLIC_MINDREPLY_BUILD_COMMIT_SHA"],
  ["version route", "versionRoute", "NEXT_PUBLIC_MINDREPLY_BUILD_BRANCH"],
  ["version route", "versionRoute", "NEXT_PUBLIC_MINDREPLY_PROJECT_PRODUCTION_URL"],
  ["version route", "versionRoute", "VERCEL_PROJECT_PRODUCTION_URL"],
  ["version route", "versionRoute", "shortSha"],
  ["health route", "healthRoute", "version:"],
  ["health route", "healthRoute", '"/api/version"'],
  ["monitor report", "monitorReport", '{ label: "version"'],
  ["monitor report", "monitorReport", '{ label: "agent-api"'],
  ["monitor report", "monitorReport", '{ label: "intake-api"'],
  ["monitor report", "monitorReport", "hasAgentShape"],
  ["monitor report", "monitorReport", "hasDecisionShape"],
  ["monitor report", "monitorReport", "functionalChecks"],
  ["monitor report", "monitorReport", "decisionApi"],
  ["monitor report", "monitorReport", "productionVersion"],
  ["monitor report", "monitorReport", "production is stale"],
  ["monitor report", "monitorReport", "matchesRun"],
  ["monitor workflow", "monitorWorkflow", "*/15 * * * *"],
  ["monitor workflow", "monitorWorkflow", "scripts/mragent-monitor-report.mjs"],
  ["monitor workflow", "monitorWorkflow", "scripts/mragent-growth-pulse.mjs"],
  ["monitor workflow", "monitorWorkflow", "scripts/mragent-short-digest.mjs"],
  ["monitor workflow", "monitorWorkflow", "mragent-monitor-status.json"],
  ["monitor workflow", "monitorWorkflow", "mragent-growth-pulse.json"],
  ["monitor workflow", "monitorWorkflow", "mragent-short-digest.json"],
  ["monitor workflow", "monitorWorkflow", "mragent-short-digest.md"],
  ["incident probe", "incidentProbe", "fallback-only-domain"],
  ["incident probe", "incidentProbe", "stale-production-domain"],
  ["incident probe", "incidentProbe", "mragent-domain-incident.json"],
  ["incident probe", "incidentProbe", "preferred-agent-api"],
  ["incident probe", "incidentProbe", "fallback-intake-api"],
  ["incident workflow", "incidentWorkflow", "workflow_dispatch"],
  ["incident workflow", "incidentWorkflow", "scripts/production-domain-incident.mjs"],
  ["incident workflow", "incidentWorkflow", "mragent-domain-incident"],
  ["growth pulse", "growthPulse", "mragent-growth-pulse.json"],
  ["growth pulse", "growthPulse", "primaryLane"],
  ["growth pulse", "growthPulse", "copyTests"],
  ["growth pulse", "growthPulse", "recommendedAction"],
  ["growth workflow", "growthWorkflow", "workflow_dispatch"],
  ["growth workflow", "growthWorkflow", "18 9 * * 1"],
  ["growth workflow", "growthWorkflow", "scripts/mragent-growth-pulse.mjs"],
  ["growth workflow", "growthWorkflow", "mragent-growth-pulse"],
  ["short digest", "shortDigest", "mragent-short-digest.json"],
  ["short digest", "shortDigest", "mragent-short-digest.md"],
  ["short digest", "shortDigest", "MRagent short digest"],
  ["short digest", "shortDigest", "Blocker:"],
  ["short digest", "shortDigest", "Promise:"],
  ["short digest", "shortDigest", "Next:"],
  ["vercel ignore", "vercelIgnore", "scripts/mragent-monitor-report.mjs"],
  ["vercel ignore", "vercelIgnore", "scripts/mragent-growth-pulse.mjs"],
  ["vercel ignore", "vercelIgnore", "scripts/mragent-short-digest.mjs"],
  ["vercel ignore", "vercelIgnore", "scripts/production-domain-incident.mjs"],
  ["vercel ignore", "vercelIgnore", "scripts/verify-live-revenue-surface.mjs"],
  ["vercel ignore", "vercelIgnore", "Live verification/report changes must be skipped."],
  ["vercel ignore", "vercelIgnore", "Reporting-only script changes must be skipped."],
  ["vercel guard workflow", "vercelGuardWorkflow", "Vercel Guard Verify"],
  ["vercel guard workflow", "vercelGuardWorkflow", "workflow_dispatch"],
  ["vercel guard workflow", "vercelGuardWorkflow", "node scripts/vercel-ignore-build.mjs --self-test"],
  ["vercel guard workflow", "vercelGuardWorkflow", "scripts/vercel-ignore-build.mjs"],
  ["manual deploy workflow", "manualDeployWorkflow", "MindReply Manual Vercel Production Deploy"],
  ["manual deploy workflow", "manualDeployWorkflow", "MINDREPLY_REPORT_REQUIRE_LIVE_PROOF: true"],
  ["manual deploy workflow", "manualDeployWorkflow", "MINDREPLY_REQUIRE_LIVE_SHA_MATCH: true"],
  ["manual deploy workflow", "manualDeployWorkflow", "Deploy prebuilt artifact to production"],
  ["manual deploy workflow", "manualDeployWorkflow", "NEXT_PUBLIC_MINDREPLY_BUILD_COMMIT_SHA"],
  ["manual deploy workflow", "manualDeployWorkflow", "NEXT_PUBLIC_MINDREPLY_BUILD_URL"],
  ["manual deploy workflow", "manualDeployWorkflow", "NEXT_PUBLIC_MINDREPLY_PROJECT_PRODUCTION_URL"],
  ["manual deploy workflow", "manualDeployWorkflow", "VERCEL_DEPLOYMENT_URL"],
  ["manual deploy workflow", "manualDeployWorkflow", "Assign public production aliases"],
  ["manual deploy workflow", "manualDeployWorkflow", 'vercel alias set "$VERCEL_DEPLOYMENT_URL" www.mind-reply.com'],
  ["manual deploy workflow", "manualDeployWorkflow", 'vercel alias set "$VERCEL_DEPLOYMENT_URL" mind-reply.com'],
  ["manual deploy workflow", "manualDeployWorkflow", "npm run verify:live-revenue"],
  ["manual deploy workflow", "manualDeployWorkflow", "Refresh owner deployment report with live proof"],
  ["manual deploy workflow", "manualDeployWorkflow", "npm run report:send"],
  ["alias ready workflow", "aliasReadyWorkflow", "MindReply Alias Ready Vercel Deployment"],
  ["alias ready workflow", "aliasReadyWorkflow", "alias-ready-deployment"],
  ["alias ready workflow", "aliasReadyWorkflow", "https://mindreply-k6qkqlmwh-angellllkr-engs-projects.vercel.app"],
  ["alias ready workflow", "aliasReadyWorkflow", "97f3e32fc6f01d17e9151e3dc8055a0d1722db9e"],
  ["alias ready workflow", "aliasReadyWorkflow", "dpl_3nfh51toARDzgM7yMUx1dSG9i2CY"],
  ["alias ready workflow", "aliasReadyWorkflow", "MINDREPLY_REQUIRE_LIVE_DEPLOYMENT_MATCH: true"],
  ["alias ready workflow", "aliasReadyWorkflow", "Deployment metadata did not include expected SHA"],
  ["alias ready workflow", "aliasReadyWorkflow", 'vercel alias set "$VERCEL_DEPLOYMENT_URL" www.mind-reply.com'],
  ["alias ready workflow", "aliasReadyWorkflow", 'vercel alias set "$VERCEL_DEPLOYMENT_URL" mind-reply.com'],
  ["alias ready workflow", "aliasReadyWorkflow", "Public version reports expected SHA"],
  ["alias ready workflow", "aliasReadyWorkflow", "npm run verify:live-revenue"],
  ["alias ready workflow", "aliasReadyWorkflow", "npm run report:send"],
  ["live revenue verifier", "liveRevenueVerifier", "MINDREPLY_EXPECTED_SHA"],
  ["live revenue verifier", "liveRevenueVerifier", "MINDREPLY_REQUIRE_LIVE_SHA_MATCH"],
  ["live revenue verifier", "liveRevenueVerifier", "version-sha-current"],
  ["live revenue verifier", "liveRevenueVerifier", "no-personal-gmail"],
  ["live revenue verifier", "liveRevenueVerifier", "Website Completion Package"],
  ["live revenue verifier", "liveRevenueVerifier", "GBP 600"],
  ["live revenue verifier", "liveRevenueVerifier", "info@mind-reply.com"],
  ["live revenue verifier", "liveRevenueVerifier", "/api/package-request"],
  ["live revenue verifier", "liveRevenueVerifier", 'request("/website-completion-package")'],
  ["live revenue verifier", "liveRevenueVerifier", "package-page-reachable"],
  ["live revenue verifier", "liveRevenueVerifier", "package-invoice-first-route"],
  ["live revenue verifier", "liveRevenueVerifier", "Invoice-first request path active"],
  ["live revenue verifier", "liveRevenueVerifier", "package-no-payment-link-required"],
  ["live revenue verifier", "liveRevenueVerifier", "billing name and billing email"],
  ["live revenue verifier", "liveRevenueVerifier", "package-scope-first"],
  ["live revenue verifier", "liveRevenueVerifier", "paymentPath"],
  ["live revenue verifier", "liveRevenueVerifier", "invoice-first unless a configured direct payment link is present"],
  ["send owner report", "sendOwnerReport", "MINDREPLY_REPORT_REQUIRE_LIVE_PROOF"],
  ["send owner report", "sendOwnerReport", "## Live Production Revenue Surface"],
  ["send owner report", "sendOwnerReport", "Live production revenue proof is required before owner email delivery."],
  ["send owner report", "sendOwnerReport", "Live production revenue proof is required before owner Slack delivery."],
  ["send owner report", "sendOwnerReport", "MINDREPLY_REPORT_SUBJECT"],
  ["report schema", "reportSchema", "productionVersion:"],
  ["report schema", "reportSchema", "live_revenue_surface:"],
  ["report schema", "reportSchema", "liveRevenueSurface:"],
  ["report schema", "reportSchema", "production_deploy_recovery:"],
  ["report schema", "reportSchema", "required_aliases:"],
  ["report schema", "reportSchema", "https://www.mind-reply.com"],
  ["report schema", "reportSchema", "https://mind-reply.com"],
  ["report schema", "reportSchema", "npm run verify:live-revenue"],
  ["report schema", "reportSchema", "no-personal-gmail"],
  ["report schema", "reportSchema", "owner_delivery_rule"],
  ["report schema", "reportSchema", "functionalChecks:"],
  ["report schema", "reportSchema", "growth_pulse:"],
  ["report schema", "reportSchema", "short_digest:"],
  ["report schema", "reportSchema", "vercel_guard:"],
  ["report schema", "reportSchema", "fast Vercel guard verification"],
  ["report schema", "reportSchema", "every 15 minutes, weekly monday"],
  ["report schema", "reportSchema", "short digest artifact for fast status updates"],
  ["report schema", "reportSchema", "preferred_agent_api: https://www.mind-reply.com/api/agent"],
  ["report schema", "reportSchema", "fallback_intake_api: https://www.mind-reply.com/api/intake"],
  ["report schema", "reportSchema", "package_request_api: https://www.mind-reply.com/api/package-request"],
  ["report schema", "reportSchema", "https://www.mind-reply.com/api/version"],
  ["vercel runbook", "vercelRunbook", "incident_probe:"],
  ["vercel runbook", "vercelRunbook", ".github/workflows/mragent-domain-incident.yml"],
  ["vercel runbook", "vercelRunbook", ".github/workflows/vercel-guard-verify.yml"],
  ["vercel runbook", "vercelRunbook", "scripts/production-domain-incident.mjs"],
  ["vercel runbook", "vercelRunbook", "scripts/mragent-growth-pulse.mjs"],
  ["vercel runbook", "vercelRunbook", "scripts/mragent-short-digest.mjs"],
];

for (const [label, file, expected] of checks) {
  const value = files[file];
  assert(value, `${file} must be loaded.`);
  includes(label, value, expected);
}

console.log("Production version contract verification passed.");
